### ISSUE TITLE
TODO before stable release

### ISSUE THREAD

**Issue by UltCombo** [es6rocks/slush-es6#7]
Just writing down a couple things so I don't forget.

- [x] Check how errors throw by gulp-6to5 are being handled in watch mode
- [x] Check if gulp-batch error handler can be removed after implementing gulp-jscs reporters (check whether gulp-6to5 and/or other plugins rely on the error handler as well) -- **resolution:** 6to5 needs the error handler, let's keep it.
- [ ] Check if dotfiles are being handled correctly (included in the package tarball and copied to generated projects) - let's zip the `tpl` in prepublish and unzip in postinstall to avoid npm tampering with our generator template files: https://github.com/npm/npm/issues/3763#issuecomment-71404018
    On second thought, zipping the entire tpl directory is a bit overkill and would bring some complications as well -- e.g. my current workflow runs tests directly in the tpl dir and thus adds some unnecessary files to it that would no longer be removed by npm's `.gitignore` handling if we just zipped the entire directory. The alternative solution I'll implement for the time being is:
   - Keep using templating language in the tpl's `package.json`, this way npm fails to parse it and doesn't apply the `files` property handling;
    - Let npm handle the `.gitignore`s to remove unnecessary files from the package. Note that `npm pack` and `npm install` will rename `.gitignore`s to `.npmignore`s so we need an `install` script to rename them back.

    These solutions seem way too fragile and not future proof (what if we want to publish template files that are ignored by `.gitignore`, such as config files?), but they work and seem to be the most effective for the current development and deployment workflows.
